### ISSUE TITLE
Authentication from own server working with Rumpel, but not data-plugs or data-market

### ISSUE THREAD

**Issue by TheAncientGoat** [Hub-of-all-Things/HAT2.0#27]
Managed to get my own server running (localhost proxied through ngrok for now), and I can access Rumple and update my details, but when trying to enable a data-plug, like social-plug.hubofallthings.com, I receive a 502 after entering my PHATA. 

The ngrok proxy throws a few `GET /data/table                  404 Not Found`, but it seems to be rumpel querying missing data sources

```
[INFO ] [08/07/2016 13:33:22] API-Access - GET:http://a5b6c56f.ngrok.io/data/table?name=events&source=facebook:404 Not Found
[INFO ] [08/07/2016 13:33:22] API-Access - GET:http://a5b6c56f.ngrok.io/data/table?name=posts&source=facebook:404 Not Found
[INFO ] [08/07/2016 13:33:22] API-Access - GET:http://a5b6c56f.ngrok.io/data/table?name=events&source=ical:404 Not Found
[INFO ] [08/07/2016 13:33:23] API-Access - GET:http://a5b6c56f.ngrok.io/data/table?name=locations&source=iphone:404 Not Found
```

**Comment by augustinas** [comment]
@TheAncientGoat Our current infrastructure setup requires that both the HAT and the data plug would be known to the MarketSquare. The 502 error results from the data plug not being able to connect to your HAT as it cannot find it in the MS registrar.
In order to circumvent the default MS integration, you will need to download the source code of respective data plug, comment out couple lines of code responsible for doing that check and run that code on your local machine/server.

For example with the Social Data Plug open up the following file https://github.com/Hub-of-all-Things/DataPlugFacebook/blob/master/app/routes/dataPlug.js and comment out lines 23-28 and line 57. That should do the trick.

**Comment by augustinas** [comment]
Issue out of date
